(() => {
const URL='https://pnomsapqqkgcvkzknujc.supabase.co',KEY='sb_publishable_EokwTiLlK_qy2Upc_0j3hw_noRX84_q';
const db=window.supabase.createClient(URL,KEY),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let activeInquiry=null,activePaymentBooking=null,activeClient=null,paymentTotals=new Map(),clientCache=[];
const pad=n=>String(n).padStart(2,'0'),ymd=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,hour=h=>`${h%12||12}:00 ${h<12?'AM':'PM'}`,shortHour=h=>`${h%12||12}${h<12?'am':'pm'}`;
const skillDefs=[['serve','Serve'],['return_score','Return'],['forehand','Forehand'],['backhand','Backhand'],['dinking','Dinking'],['footwork','Footwork'],['positioning','Positioning'],['consistency','Consistency'],['strategy','Strategy'],['confidence','Confidence']];
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2800)}
function esc(s){return String(s??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function money(n){return `₱${Number(n||0).toLocaleString('en-PH')}`}
function splitFullName(name){const p=String(name||'').trim().replace(/\s+/g,' ').split(' ').filter(Boolean);return {first:p.shift()||'',last:p.join(' '),full:String(name||'').trim().replace(/\s+/g,' ')}}
function showAdmin(session){$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#adminEmail').textContent=session.user.email||'';$('#scheduleDate').value=ymd(new Date());buildSkillFields();loadAll()}
function showLogin(){$('#adminView').classList.add('hidden');$('#loginView').classList.remove('hidden')}
async function init(){const {data:{session}}=await db.auth.getSession();session?showAdmin(session):showLogin()}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const {data,error}=await db.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error)return $('#loginError').textContent=error.message;showAdmin(data.session)});
$('#logoutBtn').onclick=async()=>{await db.auth.signOut();showLogin()};
$('#refreshBtn').onclick=loadAll;$('#scheduleDate').addEventListener('change',loadSchedule);$('#clientSearch').addEventListener('input',renderClientList);
async function loadAll(){await Promise.all([loadInquiries(),loadBookings(),loadSchedule(),loadClients()])}
async function loadInquiries(){const {data,error}=await db.from('inquiries').select('*').in('status',['new','waiting','tentative']).order('created_at',{ascending:false}).limit(50);if(error)return $('#inquiries').innerHTML=`<div class="empty">${esc(error.message)}</div>`;$('#metricInquiries').textContent=data.length;$('#inquiries').innerHTML=data.length?data.map(i=>`<article class="card"><div class="card-top"><div><h3>${esc(i.client_name)}</h3><div class="meta">${esc(i.preferred_date||'No date')} • ${i.start_hour==null?'No time':`${hour(i.start_hour)}–${hour(i.end_hour)}`}<br>${i.participant_count||1} player${Number(i.participant_count||1)>1?'s':''} • ${money(i.quoted_rate)} • ${esc(i.goal_focus||'General coaching')}<br>${esc(i.contact||'No contact')}</div></div><span class="tag ${i.status==='new'?'new':''}">${esc(i.status)}</span></div><div class="card-actions"><button class="mini confirm" data-confirm="${i.id}">Confirm</button><button class="mini" data-wait="${i.id}">Mark Waiting</button><button class="mini" data-cancel="${i.id}">Cancel</button></div></article>`).join(''):'<div class="empty">No pending inquiries.</div>';data.forEach(i=>{document.querySelector(`[data-confirm="${i.id}"]`)?.addEventListener('click',()=>openConfirm(i));document.querySelector(`[data-wait="${i.id}"]`)?.addEventListener('click',()=>setInquiry(i.id,'waiting'));document.querySelector(`[data-cancel="${i.id}"]`)?.addEventListener('click',()=>setInquiry(i.id,'cancelled'))})}
async function setInquiry(id,status){const {error}=await db.from('inquiries').update({status}).eq('id',id);if(error)return toast(error.message);toast(`Inquiry marked ${status}.`);loadInquiries()}
function openConfirm(i){activeInquiry=i;$('#confirmTitle').textContent=i.client_name;$('#confirmMeta').innerHTML=`${esc(i.preferred_date)} • ${hour(i.start_hour)}–${hour(i.end_hour)}<br>${i.participant_count||1} player${Number(i.participant_count||1)>1?'s':''} • ${esc(i.coaching_type||'Coaching session')}<br>${esc(i.contact||'No contact')}`;$('#confirmAmount').value=Number(i.quoted_rate||0);$('#confirmNote').value='';$('#confirmDialog').showModal()}
$('#confirmBookingBtn').onclick=confirmBooking;
async function findOrCreateClient(p){const full=String(p.full_name||`${p.first_name||''} ${p.last_name||''}`).trim().replace(/\s+/g,' '),contact=p.contact||null;let q=db.from('clients').select('*').ilike('full_name',full).eq('is_active',true);if(contact)q=q.eq('contact',contact);const {data:found}=await q.limit(1);if(found?.length)return found[0];const n=splitFullName(full),payload={first_name:p.first_name||n.first,last_name:p.last_name||n.last,full_name:full,name_key:full.toLowerCase(),contact,contact_key:contact?String(contact).trim().toLowerCase():null,is_active:true};const {data,error}=await db.from('clients').insert(payload).select('*').single();if(error)throw error;return data}
async function confirmBooking(){const i=activeInquiry;if(!i)return;const amount=Number($('#confirmAmount').value||0);if(i.start_hour==null||i.end_hour==null||!i.preferred_date)return toast('Inquiry has incomplete schedule details.');const {data:conflicts,error:ce}=await db.from('schedule_slots').select('start_hour,status').eq('slot_date',i.preferred_date).gte('start_hour',i.start_hour).lt('start_hour',i.end_hour).in('status',['booked','unavailable']);if(ce)return toast(ce.message);if(conflicts?.length)return toast('That time is no longer available.');const {data:participants,error:pe}=await db.from('inquiry_participants').select('*').eq('inquiry_id',i.id).order('participant_order');if(pe)return toast(pe.message);const pc=Number(i.participant_count||participants?.length||1);const {data:b,error}=await db.from('bookings').insert({session_date:i.preferred_date,start_hour:i.start_hour,end_hour:i.end_hour,client_name:i.client_name,contact:i.contact,participant_count:pc,coaching_type:i.coaching_type||`${pc} Player${pc>1?'s':''}`,rate_mode:'standard',rate_per_person:pc?amount/pc:amount,total_amount:amount,notes:$('#confirmNote').value.trim()||i.notes||null,status:'confirmed',session_status:'scheduled'}).select('id').single();if(error)return toast(error.message);try{const bp=[];let primaryClientId=null;for(const p of (participants||[])){const c=await findOrCreateClient(p);if(p.is_primary||Number(p.participant_order)===1)primaryClientId=c.id;bp.push({booking_id:b.id,client_id:c.id,participant_order:p.participant_order,first_name:p.first_name,last_name:p.last_name,full_name:p.full_name,contact:p.contact||null,contact_key:p.contact_key||null,is_primary:!!p.is_primary})}if(bp.length){const {error:e}=await db.from('booking_participants').insert(bp);if(e)throw e}if(primaryClientId)await db.from('bookings').update({client_id:primaryClientId}).eq('id',b.id);const rows=[];for(let h=i.start_hour;h<i.end_hour;h++)rows.push({slot_date:i.preferred_date,start_hour:h,status:'booked',client_name:i.client_name,contact:i.contact,coaching_type:i.coaching_type,rate:amount,booking_id:b.id});const {error:se}=await db.from('schedule_slots').upsert(rows,{onConflict:'slot_date,start_hour'});if(se)throw se;await db.from('inquiries').update({status:'confirmed'}).eq('id',i.id);$('#confirmDialog').close();toast('Booking confirmed. Client profiles updated.');loadAll()}catch(e){await db.from('booking_participants').delete().eq('booking_id',b.id);await db.from('bookings').delete().eq('id',b.id);toast(e.message||'Could not finish booking confirmation.') }}
async function loadBookings(){const today=ymd(new Date());const {data,error}=await db.from('bookings').select('*').eq('status','confirmed').gte('session_date',today).order('session_date').order('start_hour').limit(80);if(error){$('#bookings').innerHTML=`<div class="empty">${esc(error.message)}</div>`;$('#todayBookings').innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}const ids=data.map(b=>b.id);paymentTotals=new Map();if(ids.length){const {data:p}=await db.from('booking_payments').select('booking_id,amount').in('booking_id',ids);(p||[]).forEach(x=>paymentTotals.set(x.booking_id,(paymentTotals.get(x.booking_id)||0)+Number(x.amount||0)))}const balance=data.reduce((s,b)=>s+Math.max(0,Number(b.total_amount||0)-(paymentTotals.get(b.id)||0)),0);$('#metricBalance').textContent=money(balance);$('#metricBookings').textContent=data.length;const todays=data.filter(b=>b.session_date===today);$('#metricToday').textContent=todays.length;renderBookings(data,todays)}
function bookingCard(b,todayMode=false){const paid=paymentTotals.get(b.id)||0,total=Number(b.total_amount||0),bal=Math.max(0,total-paid),payState=bal<=0?'Paid':paid>0?'Partial':'Unpaid';return `<article class="card"><div class="card-top"><div><h3>${esc(b.client_name)}</h3><div class="meta">${esc(b.session_date)} • ${hour(b.start_hour)}–${hour(b.end_hour)}<br>${b.participant_count} player${b.participant_count>1?'s':''} • ${money(total)}<br>${esc(b.contact||'No contact')}</div></div><div class="tag-stack"><span class="tag">${esc(b.session_status||'scheduled')}</span><span class="tag payment ${payState.toLowerCase()}">${payState}${bal?` • ${money(bal)} due`:''}</span></div></div><div class="card-actions">${todayMode&&b.session_status!=='completed'?`<button class="mini confirm" data-complete="${b.id}">Mark Completed</button>`:''}<button class="mini" data-payment="${b.id}">Record Payment</button><button class="mini danger" data-cancel-booking="${b.id}">Cancel Booking</button></div></article>`}
function renderBookings(all,todays){$('#todayBookings').innerHTML=todays.length?todays.map(b=>bookingCard(b,true)).join(''):'<div class="empty">No coaching sessions today.</div>';$('#bookings').innerHTML=all.length?all.map(b=>bookingCard(b,false)).join(''):'<div class="empty">No upcoming confirmed bookings.</div>';all.forEach(b=>{document.querySelectorAll(`[data-cancel-booking="${b.id}"]`).forEach(x=>x.onclick=()=>cancelBooking(b));document.querySelectorAll(`[data-payment="${b.id}"]`).forEach(x=>x.onclick=()=>openPayment(b));document.querySelectorAll(`[data-complete="${b.id}"]`).forEach(x=>x.onclick=()=>setSessionStatus(b,'completed'))})}
async function setSessionStatus(b,status){if(status==='completed'&&!confirm(`Mark ${b.client_name}'s session as completed?`))return;const {error}=await db.from('bookings').update({session_status:status,session_closed_at:status==='completed'?new Date().toISOString():null}).eq('id',b.id);if(error)return toast(error.message);toast('Session marked completed.');loadBookings();loadClients()}
function openPayment(b){activePaymentBooking=b;const paid=paymentTotals.get(b.id)||0,total=Number(b.total_amount||0),bal=Math.max(0,total-paid);$('#paymentTitle').textContent=b.client_name;$('#paymentMeta').innerHTML=`${esc(b.session_date)} • ${hour(b.start_hour)}–${hour(b.end_hour)}`;$('#paymentTotal').textContent=money(total);$('#paymentPaid').textContent=money(paid);$('#paymentBalance').textContent=money(bal);$('#paymentAmount').value=bal||'';$('#paymentAmount').max=bal;$('#paymentDate').value=ymd(new Date());$('#paymentNote').value='';$('#paymentDialog').showModal()}
$('#savePaymentBtn').onclick=savePayment;
async function savePayment(){const b=activePaymentBooking;if(!b)return;const amount=Number($('#paymentAmount').value||0),paid=paymentTotals.get(b.id)||0,bal=Math.max(0,Number(b.total_amount||0)-paid);if(amount<=0)return toast('Enter a valid payment amount.');if(amount>bal)return toast('Payment cannot be greater than the remaining balance.');const {error}=await db.from('booking_payments').insert({booking_id:b.id,amount,paid_at:$('#paymentDate').value,payment_method:$('#paymentMethod').value,note:$('#paymentNote').value.trim()||null,source:'manual'});if(error)return toast(error.message);$('#paymentDialog').close();toast('Payment recorded.');loadBookings()}
async function cancelBooking(b){if(!confirm(`Cancel booking for ${b.client_name}?`))return;const {error}=await db.from('bookings').update({status:'cancelled',session_status:'cancelled',cancelled_at:new Date().toISOString()}).eq('id',b.id);if(error)return toast(error.message);await db.from('schedule_slots').delete().eq('booking_id',b.id);toast('Booking cancelled and hours reopened.');loadAll()}
async function loadSchedule(){const d=$('#scheduleDate').value||ymd(new Date());const {data,error}=await db.from('schedule_slots').select('*').eq('slot_date',d).order('start_hour');if(error)return $('#scheduleSlots').innerHTML=`<div class="empty">${esc(error.message)}</div>`;const map=new Map((data||[]).map(r=>[Number(r.start_hour),r]));if(d===ymd(new Date()))$('#metricBlocked').textContent=(data||[]).filter(r=>r.status==='unavailable').length;let html='';for(let h=8;h<22;h++){const r=map.get(h),st=r?.status||'available';html+=`<button class="slot ${st}" data-hour="${h}" ${st==='booked'?'disabled':''}><span class="slot-time">${shortHour(h)} to ${shortHour(h+1)}</span>${st==='unavailable'?'<small>Blocked</small>':st==='booked'?'<small>Booked</small>':''}</button>`}$('#scheduleSlots').innerHTML=html;$$('#scheduleSlots .slot:not([disabled])').forEach(btn=>btn.onclick=()=>toggleSlot(d,Number(btn.dataset.hour),map.get(Number(btn.dataset.hour))))}
async function toggleSlot(date,h,row){if(row?.status==='unavailable'){const {error}=await db.from('schedule_slots').delete().eq('id',row.id);if(error)return toast(error.message);toast(`${hour(h)} reopened.`)}else{const {error}=await db.from('schedule_slots').upsert({slot_date:date,start_hour:h,status:'unavailable',notes:'Blocked by Coach Kyle admin'},{onConflict:'slot_date,start_hour'});if(error)return toast(error.message);toast(`${hour(h)} blocked.`)}loadSchedule()}
async function loadClients(){const {data,error}=await db.from('clients').select('*').eq('is_active',true).order('full_name').limit(300);if(error){$('#clients').innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}clientCache=data||[];$('#metricClients').textContent=clientCache.length;renderClientList()}
function renderClientList(){const q=($('#clientSearch').value||'').trim().toLowerCase(),rows=clientCache.filter(c=>!q||c.full_name.toLowerCase().includes(q)||(c.contact||'').toLowerCase().includes(q));$('#clients').innerHTML=rows.length?rows.map(c=>`<button class="client-card" data-client="${c.id}"><span>${esc(c.full_name)}</span><small>${esc(c.contact||'No contact saved')}</small><b>View profile →</b></button>`).join(''):'<div class="empty">No matching clients.</div>';$$('[data-client]').forEach(btn=>btn.onclick=()=>openClient(btn.dataset.client))}
async function openClient(id){activeClient=clientCache.find(c=>c.id===id);if(!activeClient)return;$('#clientName').textContent=activeClient.full_name;$('#clientMeta').textContent=activeClient.contact||'No contact saved';$('#clientDialog').showModal();await loadClientDetails()}
$('#closeClientDialog').onclick=()=>$('#clientDialog').close();
async function loadClientDetails(){if(!activeClient)return;const {data:bp,error}=await db.from('booking_participants').select('booking_id').eq('client_id',activeClient.id);if(error)return toast(error.message);const ids=[...new Set((bp||[]).map(x=>x.booking_id))];let sessions=[];if(ids.length){const {data}=await db.from('bookings').select('*').in('id',ids).order('session_date',{ascending:false}).order('start_hour',{ascending:false});sessions=data||[]}const completed=sessions.filter(x=>x.session_status==='completed').length,hours=sessions.filter(x=>x.status==='confirmed').reduce((s,x)=>s+(Number(x.end_hour)-Number(x.start_hour)),0);$('#clientStats').innerHTML=`<div><span>Total sessions</span><strong>${sessions.length}</strong></div><div><span>Completed</span><strong>${completed}</strong></div><div><span>Coaching hours</span><strong>${hours}</strong></div>`;$('#clientSessions').innerHTML=sessions.length?sessions.map(s=>`<div class="timeline-item"><strong>${esc(s.session_date)} • ${hour(s.start_hour)}–${hour(s.end_hour)}</strong><small>${esc(s.coaching_type||'Coaching')} • ${esc(s.session_status)} • ${money(s.total_amount)}</small>${s.session_outcome_note?`<p>${esc(s.session_outcome_note)}</p>`:''}</div>`).join(''):'<div class="empty">No session history yet.</div>';await loadProgress()}
async function loadProgress(){if(!activeClient)return;const {data,error}=await db.from('progress_assessments').select('*').eq('client_id',activeClient.id).order('assessment_date',{ascending:false}).order('created_at',{ascending:false}).limit(30);if(error)return $('#clientProgress').innerHTML=`<div class="empty">${esc(error.message)}</div>`;if(!data.length){$('#clientProgress').innerHTML='<div class="empty">No assessment yet.</div>';return}const latest=data[0],scores=skillDefs.map(([k,l])=>latest[k]!=null?`<div class="skill-score"><span>${l}</span><strong>${latest[k]}/5</strong></div>`:'').join('');$('#clientProgress').innerHTML=`<div class="progress-latest"><span class="eyebrow">LATEST • ${esc(latest.assessment_date)}</span><div class="skill-score-grid">${scores}</div>${latest.coach_note?`<p>${esc(latest.coach_note)}</p>`:''}</div><div class="assessment-history">${data.map(a=>`<div><strong>${esc(a.assessment_date)} • ${esc(a.assessment_type)}</strong><small>${a.coach_note?esc(a.coach_note):'No note'}</small></div>`).join('')}</div>`}
function buildSkillFields(){const x=$('#skillFields');if(!x||x.children.length)return;const labels={1:'Needs work',2:'Emerging',3:'Developing',4:'Proficient',5:'Strong'};x.innerHTML='<div class="rating-scale-legend">'+Object.entries(labels).map(([n,t])=>`<span><b>${n}</b>${t}</span>`).join('')+'</div>'+skillDefs.map(([k,l])=>`<label class="rating-field"><span class="rating-field-name">${l}</span><select id="skill_${k}" class="rating-native" aria-label="${l} rating"><option value="">Not rated</option>${[1,2,3,4,5].map(n=>`<option value="${n}">${n} - ${labels[n]}</option>`).join('')}</select><div class="rating-control" data-rating-for="${k}">${[1,2,3,4,5].map(n=>`<button type="button" class="rating-chip" data-rating-skill="${k}" data-rating-value="${n}" aria-label="${l}: ${n} - ${labels[n]}">${n}</button>`).join('')}</div><span class="rating-choice-label" id="rating_status_${k}">Not rated — tap 1 to 5</span></label>`).join('');x.addEventListener('click',e=>{const b=e.target.closest('[data-rating-skill]');if(!b)return;const k=b.dataset.ratingSkill,v=b.dataset.ratingValue,select=$('#skill_'+k),control=b.closest('.rating-control'),status=$('#rating_status_'+k);if(!select||!control)return;select.value=v;control.querySelectorAll('.rating-chip').forEach(btn=>btn.classList.toggle('active',btn===b));if(status){status.textContent=`${v} - ${labels[v]}`;status.classList.add('selected')}})}
function resetProgressRatings(){skillDefs.forEach(([k])=>{const s=$('#skill_'+k);if(s)s.value='';document.querySelectorAll(`[data-rating-skill="${k}"]`).forEach(b=>b.classList.remove('active'));const status=$('#rating_status_'+k);if(status){status.textContent='Not rated — tap 1 to 5';status.classList.remove('selected')}})}$('#addProgressBtn').onclick=()=>{if(!activeClient)return;buildSkillFields();$('#progressTitle').textContent=`Assess ${activeClient.full_name}`;$('#assessmentDate').value=ymd(new Date());$('#assessmentType').value='session';$('#assessmentNote').value='';resetProgressRatings();if($('#clientDialog').open)$('#clientDialog').close();$('#progressDialog').showModal()};const reopenClient=()=>{if(activeClient&&!$('#clientDialog').open)$('#clientDialog').showModal()};$('#closeProgressDialog').onclick=()=>{$('#progressDialog').close();reopenClient()};$('#cancelProgress').onclick=()=>{$('#progressDialog').close();reopenClient()};
$('#progressForm').addEventListener('submit',async e=>{e.preventDefault();if(!activeClient)return;const payload={client_id:activeClient.id,assessment_date:$('#assessmentDate').value,assessment_type:$('#assessmentType').value,assessment_source:'coach',coach_note:$('#assessmentNote').value.trim()||null};let rated=0;skillDefs.forEach(([k])=>{const v=$('#skill_'+k).value;if(v){payload[k]=Number(v);rated++}});if(!rated&&!payload.coach_note)return toast('Add at least one skill rating or a coach note.');const {error}=await db.from('progress_assessments').insert(payload);if(error)return toast(error.message);$('#progressDialog').close();reopenClient();toast('Progress assessment saved.');loadProgress()});
init();
})();