(() => {
const URL='https://pnomsapqqkgcvkzknujc.supabase.co';
const KEY='sb_publishable_EokwTiLlK_qy2Upc_0j3hw_noRX84_q';
const db=window.supabase.createClient(URL,KEY);
const $=s=>document.querySelector(s);let activeInquiry=null;
const pad=n=>String(n).padStart(2,'0');const ymd=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;const hour=h=>`${h%12||12}:00 ${h<12?'AM':'PM'}`;
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2600)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function money(n){return `₱${Number(n||0).toLocaleString('en-PH')}`}
function showAdmin(session){$('#loginView').classList.add('hidden');$('#adminView').classList.remove('hidden');$('#adminEmail').textContent=session.user.email||'';const t=new Date();$('#scheduleDate').value=ymd(t);loadAll()}
function showLogin(){ $('#adminView').classList.add('hidden');$('#loginView').classList.remove('hidden') }
async function init(){const {data:{session}}=await db.auth.getSession();if(session)showAdmin(session);else showLogin();}
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const email=$('#email').value.trim(),password=$('#password').value;const {data,error}=await db.auth.signInWithPassword({email,password});if(error){$('#loginError').textContent=error.message;return}showAdmin(data.session)});
$('#logoutBtn').onclick=async()=>{await db.auth.signOut();showLogin()};$('#refreshBtn').onclick=loadAll;$('#scheduleDate').addEventListener('change',loadSchedule);
async function loadAll(){await Promise.all([loadInquiries(),loadBookings(),loadSchedule()])}
async function loadInquiries(){const {data,error}=await db.from('inquiries').select('*').in('status',['new','waiting','tentative']).order('created_at',{ascending:false}).limit(50);if(error){$('#inquiries').innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}$('#metricInquiries').textContent=data.length;$('#inquiries').innerHTML=data.length?data.map(i=>`<article class="card"><div class="card-top"><div><h3>${esc(i.client_name)}</h3><div class="meta">${esc(i.preferred_date||'No date')} • ${i.start_hour==null?'No time':`${hour(i.start_hour)}–${hour(i.end_hour)}`}<br>${i.participant_count||1} player${Number(i.participant_count||1)>1?'s':''} • ${money(i.quoted_rate)} • ${esc(i.goal_focus||'General coaching')}<br>${esc(i.contact||'No contact')}</div></div><span class="tag ${i.status==='new'?'new':''}">${esc(i.status)}</span></div><div class="card-actions"><button class="mini confirm" data-confirm="${i.id}">Confirm</button><button class="mini" data-wait="${i.id}">Mark Waiting</button><button class="mini" data-cancel="${i.id}">Cancel</button></div></article>`).join(''):'<div class="empty">No pending inquiries.</div>';data.forEach(i=>{document.querySelector(`[data-confirm="${i.id}"]`)?.addEventListener('click',()=>openConfirm(i));document.querySelector(`[data-wait="${i.id}"]`)?.addEventListener('click',()=>setInquiry(i.id,'waiting'));document.querySelector(`[data-cancel="${i.id}"]`)?.addEventListener('click',()=>setInquiry(i.id,'cancelled'))})}
async function setInquiry(id,status){const {error}=await db.from('inquiries').update({status}).eq('id',id);if(error)return toast(error.message);toast(`Inquiry marked ${status}.`);loadInquiries()}
function openConfirm(i){activeInquiry=i;$('#confirmTitle').textContent=i.client_name;$('#confirmMeta').innerHTML=`${esc(i.preferred_date)} • ${hour(i.start_hour)}–${hour(i.end_hour)}<br>${i.participant_count||1} player${Number(i.participant_count||1)>1?'s':''} • ${esc(i.coaching_type||'Coaching session')}<br>${esc(i.contact||'No contact')}`;$('#confirmAmount').value=Number(i.quoted_rate||0);$('#confirmNote').value='';$('#confirmDialog').showModal()}
$('#confirmBookingBtn').onclick=confirmBooking;
async function confirmBooking(){const i=activeInquiry;if(!i)return;const amount=Number($('#confirmAmount').value||0);if(i.start_hour==null||i.end_hour==null||!i.preferred_date)return toast('Inquiry has incomplete schedule details.');const {data:conflicts,error:ce}=await db.from('schedule_slots').select('start_hour,status').eq('slot_date',i.preferred_date).gte('start_hour',i.start_hour).lt('start_hour',i.end_hour).in('status',['booked','unavailable']);if(ce)return toast(ce.message);if(conflicts?.length)return toast('That time is no longer available.');const pc=Number(i.participant_count||1);const {data:b,error}=await db.from('bookings').insert({session_date:i.preferred_date,start_hour:i.start_hour,end_hour:i.end_hour,client_name:i.client_name,contact:i.contact,participant_count:pc,coaching_type:i.coaching_type||`${pc} Player${pc>1?'s':''}`,rate_mode:'standard',rate_per_person:pc?amount/pc:amount,total_amount:amount,notes:$('#confirmNote').value.trim()||i.notes||null,status:'confirmed',session_status:'scheduled'}).select('id').single();if(error)return toast(error.message);const rows=[];for(let h=i.start_hour;h<i.end_hour;h++)rows.push({slot_date:i.preferred_date,start_hour:h,status:'booked',client_name:i.client_name,contact:i.contact,coaching_type:i.coaching_type,rate:amount,booking_id:b.id});const {error:se}=await db.from('schedule_slots').upsert(rows,{onConflict:'slot_date,start_hour'});if(se){await db.from('bookings').delete().eq('id',b.id);return toast(se.message)}await db.from('inquiries').update({status:'confirmed'}).eq('id',i.id);$('#confirmDialog').close();toast('Booking confirmed and schedule blocked.');loadAll()}
async function loadBookings(){const today=ymd(new Date());const {data,error}=await db.from('bookings').select('*').eq('status','confirmed').gte('session_date',today).order('session_date',{ascending:true}).order('start_hour',{ascending:true}).limit(40);if(error){$('#bookings').innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}$('#metricBookings').textContent=data.length;$('#metricToday').textContent=data.filter(b=>b.session_date===today).length;$('#bookings').innerHTML=data.length?data.map(b=>`<article class="card"><div class="card-top"><div><h3>${esc(b.client_name)}</h3><div class="meta">${esc(b.session_date)} • ${hour(b.start_hour)}–${hour(b.end_hour)}<br>${b.participant_count} player${b.participant_count>1?'s':''} • ${money(b.total_amount)}<br>${esc(b.contact||'No contact')}</div></div><span class="tag">${esc(b.session_status)}</span></div><div class="card-actions"><button class="mini" data-cancel-booking="${b.id}">Cancel Booking</button></div></article>`).join(''):'<div class="empty">No upcoming confirmed bookings.</div>';data.forEach(b=>document.querySelector(`[data-cancel-booking="${b.id}"]`)?.addEventListener('click',()=>cancelBooking(b)))}
async function cancelBooking(b){if(!confirm(`Cancel booking for ${b.client_name}?`))return;const {error}=await db.from('bookings').update({status:'cancelled',session_status:'cancelled',cancelled_at:new Date().toISOString()}).eq('id',b.id);if(error)return toast(error.message);await db.from('schedule_slots').delete().eq('booking_id',b.id);toast('Booking cancelled and hours reopened.');loadAll()}
async function loadSchedule(){const d=$('#scheduleDate').value||ymd(new Date());const {data,error}=await db.from('schedule_slots').select('*').eq('slot_date',d).order('start_hour');if(error){$('#scheduleSlots').innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}const map=new Map((data||[]).map(r=>[Number(r.start_hour),r]));if(d===ymd(new Date()))$('#metricBlocked').textContent=(data||[]).filter(r=>r.status==='unavailable').length;let html='';for(let h=8;h<22;h++){const r=map.get(h);const st=r?.status||'available';html+=`<button class="slot ${st}" data-hour="${h}" ${st==='booked'?'disabled':''}>${hour(h)}${st==='unavailable'?'<br><small>Blocked</small>':st==='booked'?'<br><small>Booked</small>':''}</button>`}$('#scheduleSlots').innerHTML=html;document.querySelectorAll('#scheduleSlots .slot:not([disabled])').forEach(btn=>btn.onclick=()=>toggleSlot(d,Number(btn.dataset.hour),map.get(Number(btn.dataset.hour))))}
async function toggleSlot(date,h,row){if(row?.status==='unavailable'){const {error}=await db.from('schedule_slots').delete().eq('id',row.id);if(error)return toast(error.message);toast(`${hour(h)} reopened.`)}else{const {error}=await db.from('schedule_slots').upsert({slot_date:date,start_hour:h,status:'unavailable',notes:'Blocked by Coach Kyle admin'},{onConflict:'slot_date,start_hour'});if(error)return toast(error.message);toast(`${hour(h)} blocked.`)}loadSchedule()}
init();
})();