(() => {
  const CONFIG={supabaseUrl:'https://pnomsapqqkgcvkzknujc.supabase.co',supabaseKey:'sb_publishable_EokwTiLlK_qy2Upc_0j3hw_noRX84_q',facebook:'https://www.facebook.com/kylepaulo13',phone:'09637600148',startHour:8,endHour:22,baseRate:500,additionalPlayerRate:200,maxPlayers:12};
  const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
  const pad=n=>String(n).padStart(2,'0'),keyDate=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,hourName=h=>`${h%12||12}:00 ${h<12?'AM':'PM'}`,shortHour=h=>`${h%12||12}${h<12?'am':'pm'}`;
  let selectedHour=null,selectedDuration=1,scheduleMap=new Map();
  const dateInput=$('#date'),slots=$('#slots'),players=$('#players'),durationInput=$('#duration'),status=$('#availabilityStatus'),summary=$('#requestSummary'),extraPlayers=$('#extraPlayers');
  const db=window.supabase?.createClient(CONFIG.supabaseUrl,CONFIG.supabaseKey);

  function nav(){const btn=$('#menuBtn'),nav=$('#nav');if(!btn||!nav)return;btn.onclick=()=>nav.classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>nav.classList.remove('open'))}
  function minDate(){const today=new Date();dateInput.min=keyDate(today);if(!dateInput.value)dateInput.value=keyDate(today)}
  function rateFor(count){const n=Math.max(1,Math.min(CONFIG.maxPlayers,Number(count)||1));return CONFIG.baseRate+((n-1)*CONFIG.additionalPlayerRate)}
  function hourlyRate(){return rateFor(Number(players.value))}
  function totalFee(){return hourlyRate()*selectedDuration}
  function buildPlayerOptions(){if(!players)return;const current=Math.min(Number(players.value)||1,CONFIG.maxPlayers);players.innerHTML='';for(let i=1;i<=CONFIG.maxPlayers;i++){const opt=document.createElement('option');opt.value=String(i);opt.textContent=i===1?'1 player (1-on-1)':`${i} players`;players.appendChild(opt)}players.value=String(current)}
  function slotStatus(h){return scheduleMap.get(`${dateInput.value}|${h}`)||'available'}
  function maxDurationFrom(start){let count=0;for(let h=start;h<CONFIG.endHour;h++){const st=slotStatus(h);if(st==='booked'||st==='unavailable')break;count++}return count}
  function buildDurationOptions(reset=false){if(!durationInput)return;if(selectedHour===null){durationInput.innerHTML='<option value="1">Choose a start time first</option>';durationInput.disabled=true;selectedDuration=1;return}const max=maxDurationFrom(selectedHour);if(reset)selectedDuration=1;selectedDuration=Math.max(1,Math.min(selectedDuration,max||1));durationInput.innerHTML='';for(let i=1;i<=max;i++){const opt=document.createElement('option');opt.value=String(i);opt.textContent=`${i} hour${i>1?'s':''}`;durationInput.appendChild(opt)}durationInput.value=String(selectedDuration);durationInput.disabled=max<1}
  function renderSlots(){slots.innerHTML='';const end=selectedHour===null?null:selectedHour+selectedDuration;for(let h=CONFIG.startHour;h<CONFIG.endHour;h++){const st=slotStatus(h),b=document.createElement('button');b.type='button';b.className='slot';b.innerHTML=`<span class="slot-time">${shortHour(h)} to ${shortHour(h+1)}</span>${st==='booked'?'<small>Booked</small>':st==='unavailable'?'<small>Blocked</small>':''}`;if(st==='booked'||st==='unavailable'){b.disabled=true;b.classList.add(st==='booked'?'booked':'blocked')}else{b.onclick=()=>{selectedHour=h;selectedDuration=1;buildDurationOptions(true);renderSlots();updateSummary()};if(selectedHour!==null&&h>=selectedHour&&h<end)b.classList.add('selected')}slots.appendChild(b)}}
  async function loadAvailability(){selectedHour=null;selectedDuration=1;status.className='status';status.textContent='Checking live availability…';scheduleMap=new Map();buildDurationOptions();renderSlots();if(!db){status.className='status warn';status.textContent='Live schedule could not load. You can still send Coach Kyle a request through Messenger.';return}try{const {data,error}=await db.from('public_schedule').select('slot_date,start_hour,status').eq('slot_date',dateInput.value);if(error)throw error;(data||[]).forEach(r=>scheduleMap.set(`${r.slot_date}|${Number(r.start_hour)}`,r.status));renderSlots();const open=[...Array(CONFIG.endHour-CONFIG.startHour)].filter((_,i)=>slotStatus(CONFIG.startHour+i)==='available').length;status.className=open?'status ok':'status warn';status.textContent=open?`${open} coaching hour${open===1?'':'s'} currently open. Choose a start time, then select how many consecutive hours you want.`:'No open coaching hours on this date. Choose another date.'}catch(e){renderSlots();status.className='status warn';status.textContent='Live schedule is temporarily unavailable. You can still send Coach Kyle a request and he will confirm it.'}updateSummary()}
  function renderExtraPlayers(){const count=Number(players.value);extraPlayers.innerHTML='';for(let i=2;i<=count;i++){const wrap=document.createElement('div');wrap.className='field';wrap.innerHTML=`<label for="player${i}">Player ${i} full name</label><input id="player${i}" data-player-name type="text" maxlength="120" placeholder="First name and last name">`;extraPlayers.appendChild(wrap)}$$('[data-player-name]').forEach(el=>el.addEventListener('input',updateSummary))}
  function splitName(v){const parts=String(v||'').trim().replace(/\s+/g,' ').split(' ').filter(Boolean);if(parts.length<2)return null;return {first_name:parts.shift(),last_name:parts.join(' ')}}
  function participantList(){const primary=splitName($('#name').value),list=[];if(primary)list.push({...primary,contact:$('#contact').value.trim()||null});else list.push(null);$$('[data-player-name]').forEach(el=>{const p=splitName(el.value);list.push(p?{...p,contact:null}:null)});return list}
  function getForm(){return {name:$('#name').value.trim(),contact:$('#contact').value.trim(),date:dateInput.value,hour:selectedHour,duration:selectedDuration,players:Number(players.value),goal:$('#goal').value}}
  function message(){const f=getForm();if(!f.name||!f.date||f.hour===null)return '';const d=new Date(`${f.date}T00:00:00`),nice=d.toLocaleDateString('en-PH',{weekday:'long',month:'long',day:'numeric',year:'numeric'}),names=participantList().map((p,i)=>p?`${i+1}. ${p.first_name} ${p.last_name}`:`${i+1}. (not completed)`).join('\n');return `Hi Coach Kyle! I would like to request a pickleball coaching session.\n\nPrimary Player: ${f.name}\nContact: ${f.contact||'Not provided'}\nDate: ${nice}\nTime: ${hourName(f.hour)} - ${hourName(f.hour+f.duration)}\nDuration: ${f.duration} hour${f.duration>1?'s':''}\nPlayers: ${f.players}\nHourly Coaching Rate: ₱${hourlyRate().toLocaleString('en-PH')}\nEstimated Coaching Fee: ₱${totalFee().toLocaleString('en-PH')}\nGoal: ${f.goal||'General coaching'}\nCourt Fee: Not included\n\nPlayer Names:\n${names}\n\nPlease confirm if this schedule is available. Thank you!`}
  function updateSummary(){const f=getForm(),parts=[];if(f.date)parts.push(f.date);if(f.hour!==null)parts.push(`${hourName(f.hour)}–${hourName(f.hour+f.duration)}`);parts.push(`${f.players} player${f.players>1?'s':''}`);parts.push(`₱${hourlyRate().toLocaleString('en-PH')}/hr`);if(f.hour!==null&&f.duration>1)parts.push(`₱${totalFee().toLocaleString('en-PH')} total`);summary.innerHTML=`<strong>Current request</strong><br>${parts.join(' • ')}`}
  async function copyText(text){try{await navigator.clipboard.writeText(text);return true}catch{const ta=document.createElement('textarea');ta.value=text;document.body.appendChild(ta);ta.select();const ok=document.execCommand('copy');ta.remove();return ok}}
  function selectedRangeAvailable(){if(selectedHour===null)return false;for(let h=selectedHour;h<selectedHour+selectedDuration;h++){const st=slotStatus(h);if(h>=CONFIG.endHour||st==='booked'||st==='unavailable')return false}return true}
  function validate(){const f=getForm(),parts=participantList();if(f.players<1||f.players>CONFIG.maxPlayers){alert(`Maximum ${CONFIG.maxPlayers} players per session.`);return false}if(!splitName(f.name)){alert('Please enter the primary player first name and last name.');$('#name').focus();return false}if(parts.length!==f.players||parts.some(p=>!p)){alert('Please enter the first name and last name of every player.');return false}if(f.hour===null){alert('Please choose an available start time.');return false}if(!selectedRangeAvailable()){alert('One or more hours in this session are no longer available. Please choose another time or duration.');return false}return true}
  async function copyAndOpen(){if(!validate())return;const text=message();await copyText(text);status.className='status ok';status.textContent='Booking details copied. Paste them in Messenger to Coach Kyle.';window.open(CONFIG.facebook,'_blank','noopener')}
  async function sendRequest(){if(!validate())return;const f=getForm(),text=message(),btn=$('#sendRequest'),old=btn.textContent;btn.disabled=true;btn.textContent='Sending…';let sent=false;if(db){try{const type=f.players===1?'1-on-1':`${f.players} Players`;const payload={p_preferred_date:f.date,p_start_hour:f.hour,p_end_hour:f.hour+f.duration,p_participant_count:f.players,p_coaching_type:`${type} • ${f.duration} Hour${f.duration>1?'s':''}`,p_quoted_rate:totalFee(),p_source_text:text,p_goal_focus:f.goal||null,p_program_interest:null,p_participants:participantList()};const {error}=await db.rpc('submit_public_inquiry_v17d',payload);if(!error)sent=true;else console.warn(error)}catch(e){console.warn(e)}}if(sent){status.className='status ok';status.textContent='Request sent to Coach Kyle Admin. Your schedule is subject to confirmation.';btn.textContent='Request Sent';setTimeout(()=>{btn.disabled=false;btn.textContent=old},2500)}else{await copyText(text);status.className='status warn';status.textContent='Direct request could not be saved, so the booking details were copied. Opening Messenger now.';window.open(CONFIG.facebook,'_blank','noopener');btn.disabled=false;btn.textContent=old}}
  function wire(){nav();buildPlayerOptions();minDate();buildDurationOptions();renderExtraPlayers();dateInput.addEventListener('change',loadAvailability);durationInput?.addEventListener('change',()=>{selectedDuration=Math.max(1,Number(durationInput.value)||1);renderSlots();updateSummary()});players.addEventListener('change',()=>{renderExtraPlayers();updateSummary()});['name','contact','goal'].forEach(id=>$('#'+id).addEventListener('input',updateSummary));$('#copyMessenger').onclick=copyAndOpen;$('#sendRequest').onclick=sendRequest;$('#scrollBooking').onclick=()=>$('#booking').scrollIntoView({behavior:'smooth'});$('#scrollRates').onclick=()=>$('#rates').scrollIntoView({behavior:'smooth'});loadAvailability();updateSummary()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
})();